pre_package:
  - vim
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - lsb-release
  - software-properties-common
  - apt-utils

liste_package:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - kubelet
  - kubeadm
  - kubectl
