---

- name: Initialize the cluster
  ansible.builtin.shell: kubeadm init --pod-network-cidr=10.0.0.0/16
  args:
    chdir: $HOME
  register: kubeadm_init_result
  changed_when: kubeadm_init_result.rc == 0
  creates: cluster_initialized.txt

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ user }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ user }}/.kube/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Install calico Pod network
  ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml
  args:
    chdir: $HOME

- name: Install calico custom resource
  ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml
  args:
    chdir: $HOME
