---

- name: Initialize the cluster
  ansible.builtin.shell: sudo kubeadm init --pod-network-cidr=10.0.0.0/16
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ user }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ user }}/.kube/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
