---

- name: Check if cluster_initialized.txt exists
  stat:
    path: "/home/{{ adm1 }}/cluster_initialized.txt"
  register: file_check

- name: Initialize the cluster
  ansible.builtin.shell: kubeadm init --pod-network-cidr=10.0.0.0/16
  when: file_check.stat.exists == False

- name: Create cluster_initialized.txt
  ansible.builtin.file:
    path: "/home/{{ adm1 }}/cluster_initialized.txt"
    state: touch
  when: file_check.stat.exists == False

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ adm1 }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ adm1 }}/.kube/config"
    owner: "{{ adm1 }}"
    group: "{{ adm1 }}"
    mode: "0644"

- name: Install calico Pod network
  ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml
  args:
    chdir: $HOME

- name: Install calico custom resource
  ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml
  args:
    chdir: $HOME
